config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'request' => 'static_pages#requestLocation'

  get 'help' => 'static_pages#help'

  get 'about' => 'static_pages#about'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def requestLocation
  end

  def help
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
  # Returns the full title on a per-page basis.       # Documentation comment
  def full_title(page_title = '', shortTitle = false)         # Method def, optional arg
    base_title = "Rhode Trip"                       # Variable assignment
    if page_title.empty? or shortTitle                             # Boolean test
      base_title                                      # Implicit return
    else
      "#{page_title} | #{base_title}"                 # String interpolation
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>  
    <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCP89_ebYuDcoJsqXEYVP5K5Y0d4ktCyQ8">
    </script>
    <script type="text/javascript">
      function initialize() {
        var mapOptions = {
          center: { lat: 41.8236, lng: -71.4222},
          zoom: 10
        };
        var map = new google.maps.Map(document.getElementById('map-canvas'),
            mapOptions);
      }
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
</head>
<body>

    <!-- Header -->

   <header class="primary-header container group">
      <h1 class="logo">
         <%= link_to "Code Island".html_safe, root_path %>
      </h1>
      <nav class="nav primary-nav">
        <ul>
          <li><%= link_to "Home", root_path %></li><!--
          --><li><%= link_to "Request", request_path %></li><!--
          --><li><%= link_to "Help", help_path %></li><!--
          --><li><%= link_to "About", about_path %></li>
        </ul>
      </nav>
    </header>

	<%= yield %>

    <!-- Footer -->

    <footer class="primary-footer container group">

      <nav class="nav">
        <ul>
          <li><%= link_to "Home", root_path %></li><!--
          --><li><%= link_to "Request", request_path %></li><!--
          --><li><%= link_to "Help", help_path %></li><!--
          --><li><%= link_to "About", about_path %></li>
          <%= image_tag("home/logo_print.png", alt: "Logo") %>
        </ul>
      </nav>
      <div class="logo-top">
      </div>
      <div class="logo-center">
      </div>
      <div class="logo-bottom">
      </div>
      <div class="footer">
        <p>
        <span class="screen_only">&copy; Code Island / </span>
          <%= link_to "Brown University’s TRI Lab at 10 Davol Square, Providence, RI 02903", about_path %>/
          <%= link_to "info@code-island.com", "mailto:info@code-island.com" %> / (401) XXX-XXXX
        </p>
      </div>
    </footer>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

    <!-- Lead -->

    <section class="row-alt">
      <div class="lead container">
        <h1><%= full_title(yield(:title), true) %> - Code Island</h1>
        <p>Since 2014</p>
      </div>
    </section>

     <section class="row">
      <div class="grid">
          <div class="col-2-3">
		      <p>
		        Code Island is the official <a href="http://codeforamerica.org/">Code for America</a> brigade in Rhode Island. We are an all-volunteer organization of people looking to improve our community through technology.
		      </p>
		      <p>
		        As a general rule, Code Island holds a <a href="http://www.meetup.com/Rhode-Island-Code-for-America-Brigade/">meetup</a> the first and third Tuesday of every month at 6pm at <a href="https://www.google.com/maps/place/10+Davol+Square,+Providence,+RI+02903/@41.824152,-71.4398007,13z/data=!4m2!3m1!1s0x89e4456a8646dbf1:0x2259e0f433c149cf?hl=en">Brown University’s TRI Lab at 10 Davol Square</a>. Our meetups are free and open to anyone who wants to contribute to our work.
		      </p>
		      <p>Stay in Touch</p>
		      <ul>
            	  <li>Check out our projects over on our <%= link_to image_tag("Social/github.png", class: "twitter", alt: "GitHub") + " Github repository", "https://github.com/codeisland/" %></li>
            	  <li>Follow us <%= link_to image_tag("Social/twitter.png", class: "twitter", alt: "@code_island") + " @Code_island", "http://www.twitter.com/code_island" %> on Twitter</li>
            	  <li>Send us <%= link_to image_tag("Social/e-mail.png", class: "twitter", alt: "Email") + " info", "mailto:info@code-island.org" %> on old-fashion Email</li>
            	  <li>Like us <%= link_to image_tag("Social/facebook.png", class: "twitter", alt: "Facebook") + " Code Island Brigade", "https://www.facebook.com/codeislandbrigade" %></li>
            	  <li>Join our <%= link_to image_tag("Social/google.png", class: "twitter", alt: "Google+") + "Google+ community", "https://plus.google.com/u/0/communities/112228497378493874687" %></li>
		      </ul>
          </div>
      </div>
    </section>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

    <!-- Lead -->

    <section class="row-alt">
      <div class="lead container">
        <h1><%= full_title(yield(:title), true) %></h1>
      </div>
    </section>

	<div class="col-1-3">Menu: <br> Tips,<br> Ticks, <br>List of Places</div><!--

	--><div id="map-canvas" class="col-2-3"></div>

app/views/static_pages/requestLocation.html.erb
<% provide(:title, "Request") %>

    <!-- Lead -->

    <section class="row-alt">
      <div class="lead container">
        <h1><%= full_title(yield(:title), true) %> - Request</h1>
      </div>
    </section>

     <section class="row">
      <div class="grid">
          <div class="col-2-3">
		      <p>
		      	Request a location for Code Island's <%= full_title(yield(:title), true) %>!
		      </p>
          </div>
      </div>
    </section>